server:
  port: 9000
spring:
  jmx:
    default-domain: online-bank
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
  application:
    name: online-bank
  banner:
    location: classpath:banner.txt

GLOBAL_PROPERTY_PATH: D:\MOOC\CaseStudy\OnlineBank\Properties\Global.yml
PROPERTY_PATH:  D:\MOOC\CaseStudy\OnlineBank\Properties\online-bank.yml