server:
  port: 8000
spring:
  devtools:
    livereload:
      enabled: true
  jmx:
    default-domain: facebook
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: NON_NULL
    serialization.write_dates_as_timestamps: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
  application:
    name: facebook
  banner:
    location: classpath:banner.txt
PROPERTY_PATH: ${user.dir}/properties/facebook.yml